[package]
name = "pprint_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "0.13.0", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.44.2", features = ["full"] }
